/* Sidebar, by M
 *
 * Three jobs, all against the SB-* conventions the firm pack bakes in:
 *   1. Attorney switch: replace the contents of the SB-SIG / SB-CERT /
 *      SB-CAPTION slots (fragments come from firm.json, generated by the
 *      pack builder). Control-first: if a rich-text content control with
 *      the SB- tag is visible to the API, replace through it so the
 *      control survives the swap; otherwise fall back to the formatting
 *      fingerprint finders for untagged imported documents.
 *   2. Defense bank: browse/search the pack's modules (modules.json),
 *      insert one as live-numbered content (the defense heading style
 *      joins the document's ordinalText list), remove one and let Word
 *      renumber.
 *   3. Finalize: strip the SB-* controls (content kept) so the document
 *      is plain Word content for filing. Refuses while the signature
 *      block carries the pack's refuse marker (an unlicensed signer).
 *
 * Defense fragments carry no styles/numbering parts, so inserted headings
 * bind to the destination's existing machinery; the machinery parts are
 * spliced in only when the document has no defense-heading paragraphs.
 */
"use strict";

let DATA = null;   // modules.json
let FIRM = null;   // firm.json
let CONV = null;   // FIRM.conventions
let WHEREFORE_RX = /^WHEREFORE/;  // recompiled from CONV at boot

const SLOT_ORDER = ["SB-SIG", "SB-CERT", "SB-CAPTION"];
const SLOT_LABELS = {
  "SB-SIG": "Signature",
  "SB-CERT": "Certificate",
  "SB-CAPTION": "Caption",
};

function slotLabel(tag) {
  if (SLOT_LABELS[tag]) return SLOT_LABELS[tag];
  const bare = tag.replace(/^SB-/, "").toLowerCase();
  return bare.charAt(0).toUpperCase() + bare.slice(1);
}

/* Short labels keep the post-switch telemetry line readable in a narrow
 * pane: "Sig ✓ control kept · Cert ✓ layout". */
const SLOT_SHORT = {
  "SB-SIG": "Sig",
  "SB-CERT": "Cert",
  "SB-CAPTION": "Caption",
};

function slotShort(tag) {
  return SLOT_SHORT[tag] || slotLabel(tag);
}

const $ = (id) => document.getElementById(id);

const ONES = ["", "FIRST", "SECOND", "THIRD", "FOURTH", "FIFTH", "SIXTH",
  "SEVENTH", "EIGHTH", "NINTH", "TENTH", "ELEVENTH", "TWELFTH",
  "THIRTEENTH", "FOURTEENTH", "FIFTEENTH", "SIXTEENTH", "SEVENTEENTH",
  "EIGHTEENTH", "NINETEENTH"];
const TENS = ["", "", "TWENTY", "THIRTY", "FORTY", "FIFTY", "SIXTY",
  "SEVENTY", "EIGHTY", "NINETY"];
const TENS_ORD = ["", "", "TWENTIETH", "THIRTIETH", "FORTIETH", "FIFTIETH",
  "SIXTIETH", "SEVENTIETH", "EIGHTIETH", "NINETIETH"];

function ordinalWord(n) {
  if (n < 20) return ONES[n] || String(n);
  if (n < 100) {
    const t = Math.floor(n / 10), o = n % 10;
    return o === 0 ? TENS_ORD[t] : TENS[t] + "-" + ONES[o];
  }
  if (n === 100) return "ONE HUNDREDTH";
  if (n < 200) return "ONE HUNDRED " + ordinalWord(n - 100);
  return String(n) + "TH";
}

function setStatus(msg, cls) {
  const el = $("status");
  el.textContent = msg;
  el.className = cls || "";
}

function fail(err) {
  console.error(err);
  let msg = err.message || String(err);
  if (err.debugInfo && err.debugInfo.errorLocation) {
    msg += " (" + err.debugInfo.errorLocation + ")";
  }
  setStatus("Word said no: " + msg, "err");
}

function licensedNames() {
  return Object.values(FIRM.attorneys)
    .filter((a) => a.licensed)
    .map((a) => a.display)
    .join(" or ");
}

/* ---------------------------------------------------------- document scan */

function isBoundary(p) {
  if (p.style === CONV.defense_style) return true;
  if (WHEREFORE_RX.test((p.text || "").trim())) return true;
  if (p.alignment === Word.Alignment.centered) return true;
  if (typeof p.leftIndent === "number" && p.leftIndent >= 250) return true;
  return false;
}

async function loadParagraphs(ctx) {
  const paras = ctx.document.body.paragraphs;
  paras.load("items/style,items/text,items/alignment,items/leftIndent," +
             "items/firstLineIndent");
  await ctx.sync();
  return paras.items;
}

/* Control-first slot finding (decision D7): the product plants plain
 * rich-text content controls tagged SB-*, which the JS API surfaces on
 * every host since WordApi 1.1. Look for the tagged control before
 * anything else; replacing through it keeps the control alive for the
 * next switch.
 */
async function findControl(ctx, tag) {
  const ccs = ctx.document.contentControls;
  ccs.load("items/tag,items/title");
  await ctx.sync();
  return ccs.items.find((c) => (c.tag || "") === tag) || null;
}

/* Fingerprint fallback for documents with no visible SB- controls (files
 * a firm imports from outside the product). The blocks are found the way
 * a reader finds them, driven by the pack's conventions. Each finder
 * returns [start, end) paragraph indexes or null.
 */
function findSigRun(items) {
  for (let i = 0; i < items.length; i++) {
    if ((items[i].text || "").trim() === CONV.sig_open_text &&
        (items[i].leftIndent || 0) >= 250) {
      let j = i + 1;
      while (j < items.length && (items[j].leftIndent || 0) >= 250) j++;
      return [i, j];
    }
  }
  return null;
}

function findCertRun(items) {
  // last contiguous run of 3.5" first-line-indent paragraphs whose first
  // line is a conformed signature (s/ or /s/)
  let best = null;
  for (let i = 0; i < items.length; i++) {
    const t = (items[i].text || "").trim();
    if ((items[i].firstLineIndent || 0) >= 250 &&
        (t.startsWith("s/") || t.startsWith("/s/"))) {
      let j = i + 1;
      while (j < items.length && (items[j].firstLineIndent || 0) >= 250 &&
             !(items[j].text || "").trim().startsWith("s/") &&
             !(items[j].text || "").trim().startsWith("/s/")) j++;
      best = [i, j];
      i = j - 1;
    }
  }
  return best;
}

function findCaptionRun(items) {
  // the court-line stack: centered paragraphs from the top of the document
  // down to (not including) the e-filing marker line
  const stop = items.findIndex(
    (p) => (p.text || "").trim() === CONV.efile_marker);
  if (stop <= 0) return null;
  for (let i = 0; i < stop; i++) {
    if (items[i].alignment !== Word.Alignment.centered) return null;
  }
  return [0, stop];
}

const SLOT_FINDERS = {
  "SB-SIG": findSigRun,
  "SB-CERT": findCertRun,
  "SB-CAPTION": findCaptionRun,
};

/* Each defense: {start, end} paragraph indexes (end exclusive). */
function scanDefenses(items) {
  const defs = [];
  items.forEach((p, i) => {
    if (p.style === CONV.defense_style) defs.push({ start: i, end: i + 1 });
  });
  defs.forEach((d, k) => {
    let j = d.start + 1;
    while (j < items.length && !isBoundary(items[j])) j++;
    d.end = j;
    d.snippet = j > d.start + 1
      ? (items[d.start + 1].text || "").trim().slice(0, 70)
      : "(no body)";
    d.ordinal = k + 1;
  });
  return defs;
}

/* -------------------------------------------------------- attorney switch */

async function switchAttorney(who) {
  const att = FIRM.attorneys[who];
  const frags = att.frags || {};
  const slots = SLOT_ORDER.map((tag) =>
    [tag, $("slot-" + tag), slotLabel(tag)]);
  // Followup 6 telemetry: one record per slot saying which mechanism ran
  // ("control", "layout", "missing") and, for the control path, whether
  // the SB- control survived its own replace. Windows lost controls after
  // control-first swaps while Mac kept them; this pins which path ran.
  const swaps = [];
  try {
    await Word.run(async (ctx) => {
      const lines = [];
      for (const [tag, box, label] of slots) {
        if (!box || !box.checked) {
          swaps.push({ slot: tag, mech: "missing", note: "slot unchecked" });
          continue;
        }
        if (!frags[tag]) {
          swaps.push({ slot: tag, mech: "missing",
                       note: "attorney has no frag" });
          lines.push(label + ": " + att.display + " has no " +
                     label.toLowerCase() + " block");
          continue;
        }
        // control first: a visible SB- control is the product's own slot,
        // and replacing through it keeps the control for the next switch
        const cc = await findControl(ctx, tag);
        if (cc) {
          cc.insertOoxml(frags[tag], Word.InsertLocation.replace);
          await ctx.sync();
          // re-query immediately: did the control survive the replace?
          const still = await findControl(ctx, tag);
          const survived = !!still;
          swaps.push({ slot: tag, mech: "control", survived: survived });
          lines.push(slotShort(tag) + " ✓ control " +
                     (survived ? "kept" : "lost"));
          continue;
        }
        // fallback: formatting fingerprint. One slot per pass, paragraphs
        // re-scanned each time: a replace shifts every index after it.
        const items = await loadParagraphs(ctx);
        const run = SLOT_FINDERS[tag] ? SLOT_FINDERS[tag](items) : null;
        if (!run) {
          swaps.push({ slot: tag, mech: "layout", found: false });
          lines.push(label + ": block not found in this document");
          continue;
        }
        const range = items[run[0]].getRange()
          .expandTo(items[run[1] - 1].getRange());
        range.insertOoxml(frags[tag], Word.InsertLocation.replace);
        await ctx.sync();
        swaps.push({ slot: tag, mech: "layout", found: true });
        lines.push(slotShort(tag) + " ✓ layout");
      }
      console.log("[sidebar] swap telemetry",
        JSON.stringify({ attorney: att.display, swaps: swaps }));
      setStatus(lines.length ? att.display + ": " + lines.join(" · ")
                             : "No slots checked.", "ok");
    });
  } catch (e) { fail(e); }
}

/* ----------------------------------------------------------- defense bank */

function modulePkg(mod, needMachinery) {
  const P = DATA.pkg;
  return P.open + P.docOpen + mod.bodyXml + P.docClose +
    (needMachinery ? P.machineryParts : "") + P.close;
}

async function addDefense(key) {
  const mod = DATA.modules.find((m) => m.key === key);
  try {
    await Word.run(async (ctx) => {
      const items = await loadParagraphs(ctx);
      const defs = scanDefenses(items);
      const pkg = modulePkg(mod, defs.length === 0);
      // Three quirks of this Word build shape the insert:
      //   1. Paragraph.insertOoxml throws InvalidArgument outright.
      //   2. Range.insertOoxml at a COLLAPSED point merges the payload
      //      inline (paragraph marks dropped).
      //   3. A leading EMPTY paragraph in a range-replace payload is
      //      silently swallowed.
      // So: plant the heading and a holder through the plain paragraph
      // API, style the heading by name (the ordinalText list renders its
      // text), and range-replace the holder with the bodies-only payload.
      let anchor = null;
      if (defs.length) {
        const last = defs[defs.length - 1];
        anchor = last.end < items.length ? items[last.end] : null;
      } else {
        const wf = items.findIndex((p) => WHEREFORE_RX.test((p.text || "").trim()));
        anchor = wf >= 0 ? items[wf] : null;
      }
      const body = ctx.document.body;
      const headingP = anchor
        ? anchor.insertParagraph("", Word.InsertLocation.before)
        : body.insertParagraph("", Word.InsertLocation.end);
      const holder = anchor
        ? anchor.insertParagraph("", Word.InsertLocation.before)
        : body.insertParagraph("", Word.InsertLocation.end);
      await ctx.sync();
      holder.getRange().insertOoxml(pkg, Word.InsertLocation.replace);
      await ctx.sync();
      // style AFTER the ooxml lands: the bootstrap payload carries the
      // style definitions for a machinery-less document
      headingP.style = CONV.defense_style;
      await ctx.sync();
      setStatus("Added as the " + ordinalWord(defs.length + 1) +
                " DEFENSE: " + mod.label +
                (mod.tag ? "  (delete the " + mod.tag + " tag if kept)" : ""),
                "ok");
    });
    await refreshCurrent();
  } catch (e) { fail(e); }
}

async function removeDefense(ordinal) {
  try {
    await Word.run(async (ctx) => {
      const items = await loadParagraphs(ctx);
      const defs = scanDefenses(items);
      const d = defs[ordinal - 1];
      if (!d) { setStatus("That defense is gone already - refreshed.", "err"); return; }
      for (let i = d.start; i < d.end; i++) items[i].delete();
      await ctx.sync();
      setStatus("Removed the " + ordinalWord(ordinal) + " DEFENSE. " +
                "Everything below renumbered itself.", "ok");
    });
    await refreshCurrent();
  } catch (e) { fail(e); }
}

/* --------------------------------------------------------------- finalize */

async function finalize() {
  try {
    await Word.run(async (ctx) => {
      const notYet = ctx.document.body.search(CONV.refuse_sign_marker,
                                              { matchCase: false });
      notYet.load("items");
      await ctx.sync();
      if (notYet.items.length) {
        setStatus("Refused: the signature block still says " +
                  CONV.refuse_sign_marker + ". Switch to " +
                  licensedNames() + " first.", "err");
        return;
      }
      const all = ctx.document.contentControls;
      all.load("items/tag,items/title");
      await ctx.sync();
      let n = 0;
      for (const cc of all.items) {
        if ((cc.tag || "").startsWith("SB-")) { cc.delete(true); n++; }
      }
      if (n) await ctx.sync();
      if (n) {
        setStatus("Stripped " + n + " content control" + (n > 1 ? "s" : "") +
                  " (content kept). The document is filing-clean.", "ok");
      } else {
        setStatus("No SB- controls were visible to Word's API in this " +
                  "document, so there was nothing Sidebar could strip from " +
                  "here. Controls never print or export, so filing as PDF " +
                  "is safe as-is. For a guaranteed clean .docx, run the " +
                  "engine's finalize tool on the saved file.", "ok");
      }
    });
  } catch (e) { fail(e); }
}

/* ------------------------------------------------------------- rendering */

function partValue(p) { return typeof p === "string" ? p : p.key; }
function partTitle(p) {
  return typeof p === "string" ? p : p.title.replace(/^PART [IVX]+ - /, "");
}

function renderBank() {
  const q = $("def-search").value.trim().toLowerCase();
  const part = $("def-part").value;
  const list = $("def-list");
  list.innerHTML = "";
  const hits = DATA.modules.filter((m) =>
    (!part || m.part === part) && (!q || m.search.includes(q)));
  list.dataset.empty = "No defense matches.";
  for (const m of hits) {
    const row = document.createElement("div");
    row.className = "mod";
    const head = document.createElement("div");
    head.className = "mod-head";
    const label = document.createElement("span");
    label.className = "mod-label";
    label.textContent = m.label;
    label.title = "Show the defense text";
    if (m.tag) {
      const chip = document.createElement("span");
      chip.className = "chip";
      chip.textContent = m.tag.replace(/[\[\]]/g, "");
      label.appendChild(chip);
    }
    const btn = document.createElement("button");
    btn.textContent = "Add";
    btn.addEventListener("click", () => addDefense(m.key));
    head.append(label, btn);
    row.appendChild(head);
    if (m.note) {
      const note = document.createElement("div");
      note.className = "mod-note";
      note.textContent = m.note;
      row.appendChild(note);
    }
    const prev = document.createElement("div");
    prev.className = "mod-preview";
    prev.textContent = m.preview;
    prev.hidden = true;
    row.appendChild(prev);
    label.addEventListener("click", () => { prev.hidden = !prev.hidden; });
    list.appendChild(row);
  }
}

async function refreshCurrent() {
  const list = $("cur-list");
  list.dataset.empty = "No live-numbered defenses in this document.";
  try {
    await Word.run(async (ctx) => {
      const items = await loadParagraphs(ctx);
      const defs = scanDefenses(items);
      list.innerHTML = "";
      for (const d of defs) {
        const row = document.createElement("div");
        row.className = "cur";
        const head = document.createElement("div");
        head.className = "cur-head";
        const ord = document.createElement("span");
        ord.className = "cur-ord";
        ord.textContent = ordinalWord(d.ordinal) + " DEFENSE";
        const btn = document.createElement("button");
        btn.className = "remove";
        btn.textContent = "Remove";
        head.append(ord, btn);
        const snip = document.createElement("div");
        snip.className = "cur-snip";
        snip.textContent = d.snippet;
        row.append(head, snip);
        btn.addEventListener("click", () => {
          if (row.querySelector(".confirm")) return;
          const c = document.createElement("div");
          c.className = "confirm";
          c.textContent = "Delete " + (d.end - d.start) + " paragraph" +
            (d.end - d.start > 1 ? "s" : "") + " (“" +
            d.snippet.slice(0, 40) + "...”)? The rest renumber.";
          const btns = document.createElement("div");
          btns.className = "btn-row";
          const yes = document.createElement("button");
          yes.className = "yes";
          yes.textContent = "Delete";
          yes.addEventListener("click", () => removeDefense(d.ordinal));
          const no = document.createElement("button");
          no.textContent = "Keep";
          no.addEventListener("click", () => c.remove());
          btns.append(yes, no);
          c.appendChild(btns);
          row.appendChild(c);
        });
        list.appendChild(row);
      }
    });
  } catch (e) { fail(e); }
}

function renderSlots() {
  // one checkbox per slot the firm's attorneys actually carry, in the
  // product's canonical order; unknown SB- tags render after the known ones
  const row = $("slot-row");
  row.innerHTML = "";
  const present = new Set();
  for (const a of Object.values(FIRM.attorneys)) {
    for (const tag of Object.keys(a.frags || {})) present.add(tag);
  }
  const ordered = SLOT_ORDER.filter((t) => present.has(t))
    .concat([...present].filter((t) => !SLOT_ORDER.includes(t)).sort());
  for (const tag of ordered) {
    const label = document.createElement("label");
    const box = document.createElement("input");
    box.type = "checkbox";
    box.id = "slot-" + tag;
    box.checked = tag !== "SB-CAPTION";
    label.append(box, " " + slotLabel(tag));
    row.appendChild(label);
  }
}

function renderAttorneys() {
  const row = $("attorney-row");
  row.innerHTML = "";
  for (const [key, a] of Object.entries(FIRM.attorneys)) {
    const btn = document.createElement("button");
    btn.className = "attorney" + (a.licensed ? "" : " ghost");
    btn.textContent = a.button;
    const has = Object.keys(a.frags || {}).map((t) => slotLabel(t));
    btn.title = a.display + " swaps: " + (has.join(", ") || "nothing");
    btn.addEventListener("click", () => switchAttorney(key));
    row.appendChild(btn);
  }
}

/* ------------------------------------------------------------ diagnostics */

/* Storage spike (feeds ADR-001 on firm-library storage): can a pack-sized
 * blob live in this webview's storage, and does it survive a Word restart?
 * The ritual: run once today (first run on this machine), close Word, run
 * again (SURVIVED), run again tomorrow. Nothing here clears the stored
 * record; the survival check depends on it staying put.
 */

let DIAG_LAST = null;   // latest results object; the Copy button copies this

function diagLines(res) {
  if (res.kind === "control-census") {
    const head = res.error
      ? ["census failed: " + res.error]
      : [res.count + " content control" + (res.count === 1 ? "" : "s") +
         " visible to the API"];
    return head.concat((res.controls || []).map(
      (c) => "  " + c.tag + " · " + c.title));
  }
  return (res.rows || []).map(
    (r) => (r.ok ? "✓ " : "✗ ") + r.name + ": " + r.detail);
}

function renderDiag(res) {
  DIAG_LAST = res;
  $("diag-out").textContent =
    diagLines(res).join("\n") + "\n\n" + JSON.stringify(res);
}

/* FNV-1a over every 1024th byte: cheap integrity check for the 10 MB
 * record, deterministic across runs and platforms. */
function fnvSample(bytes) {
  let h = 0x811c9dc5;
  for (let i = 0; i < bytes.length; i += 1024) {
    h = Math.imul(h ^ bytes[i], 0x01000193) >>> 0;
  }
  return ("0000000" + h.toString(16)).slice(-8);
}

function idbOpen() {
  return new Promise((resolve, reject) => {
    if (typeof indexedDB === "undefined") {
      reject(new Error("indexedDB unsupported"));
      return;
    }
    const req = indexedDB.open("sidebar-spike", 1);
    req.onupgradeneeded = () => {
      if (!req.result.objectStoreNames.contains("packs")) {
        req.result.createObjectStore("packs", { keyPath: "id" });
      }
    };
    req.onsuccess = () => resolve(req.result);
    req.onerror = () => reject(req.error || new Error("indexedDB open failed"));
    req.onblocked = () => reject(new Error("indexedDB open blocked"));
  });
}

function idbGet(db, key) {
  return new Promise((resolve, reject) => {
    const rq = db.transaction("packs", "readonly").objectStore("packs")
      .get(key);
    rq.onsuccess = () => resolve(rq.result || null);
    rq.onerror = () => reject(rq.error || new Error("indexedDB get failed"));
  });
}

function idbPut(db, val) {
  return new Promise((resolve, reject) => {
    const tx = db.transaction("packs", "readwrite");
    tx.objectStore("packs").put(val);
    tx.oncomplete = () => resolve();
    tx.onerror = () => reject(tx.error || new Error("indexedDB put failed"));
    tx.onabort = () => reject(tx.error || new Error("indexedDB put aborted"));
  });
}

async function runSpike() {
  if (runSpike.busy) return;
  runSpike.busy = true;
  const res = { when: new Date().toISOString(), kind: "storage-spike",
                rows: [] };
  const push = (name, ok, detail) => {
    res.rows.push({ name: name, ok: !!ok, detail: String(detail) });
    renderDiag(res);   // progressive render; the 10 MB step takes a moment
  };
  const nowMs = () => (typeof performance !== "undefined" && performance.now)
    ? performance.now() : Date.now();
  let platform = "unknown";
  let persistedNow = "unsupported";
  let survival = "no verdict";
  try {
    // 1. env
    try {
      const oc = (typeof Office !== "undefined" && Office.context)
        ? Office.context : null;
      if (oc && oc.platform) platform = String(oc.platform);
      const bits = ["platform=" + platform];
      if (oc && oc.diagnostics) {
        bits.push("host=" + oc.diagnostics.host + " " +
                  oc.diagnostics.version);
      }
      bits.push("ua=" + String(navigator.userAgent || "").slice(0, 80));
      bits.push("partitionKey " +
        (oc && typeof oc.partitionKey !== "undefined"
          ? "defined" : "not defined"));
      push("env", true, bits.join(" | "));
    } catch (e) { push("env", false, e.message || String(e)); }

    // 2. persisted
    try {
      if (navigator.storage && navigator.storage.persisted) {
        const was = await navigator.storage.persisted();
        const got = navigator.storage.persist
          ? await navigator.storage.persist() : "unsupported";
        persistedNow = String(got);
        push("persisted", true, "persisted()=" + was + " persist()=" + got);
      } else {
        push("persisted", false, "navigator.storage.persisted unsupported");
      }
    } catch (e) { push("persisted", false, e.message || String(e)); }

    // 3. estimate
    try {
      if (navigator.storage && navigator.storage.estimate) {
        const est = await navigator.storage.estimate();
        const mb = (n) => ((n || 0) / 1048576).toFixed(1) + " MB";
        push("estimate", true,
             "usage=" + mb(est.usage) + " quota=" + mb(est.quota));
      } else {
        push("estimate", false, "navigator.storage.estimate unsupported");
      }
    } catch (e) { push("estimate", false, e.message || String(e)); }

    // 4. localStorage; the 100 KB payload stays behind as a survival marker
    try {
      const prior = localStorage.getItem("sb-spike-ls-ts");
      const payload = "S".repeat(102400);
      localStorage.setItem("sb-spike-ls", payload);
      const back = localStorage.getItem("sb-spike-ls") || "";
      const ok = back.length === payload.length;
      localStorage.setItem("sb-spike-ls-ts", new Date().toISOString());
      push("localStorage", ok, "100 KB roundtrip " +
        (ok ? "ok" : "length mismatch (" + back.length + ")") +
        (prior ? " · marker survived from " + prior
               : " · first marker written"));
    } catch (e) { push("localStorage", false, e.message || String(e)); }

    // 5. IndexedDB survival check FIRST, before this run's write
    let db = null;
    try {
      db = await idbOpen();
      const rec = await idbGet(db, "pack-sim");
      if (!rec) {
        survival = "first run on this machine";
        push("idb-survival", true, survival);
      } else if (rec.data && fnvSample(rec.data) === rec.checksum) {
        survival = "SURVIVED from " + rec.ts + ", 10 MB intact";
        push("idb-survival", true, survival);
      } else {
        survival = "corrupt";
        push("idb-survival", false,
             "record present but corrupt (stored " + rec.checksum + ")");
      }
    } catch (e) {
      survival = "indexedDB unavailable";
      push("idb-survival", false, e.message || String(e));
    }

    // 6. IndexedDB write: 10 MB deterministic pattern, checksum, roundtrip
    try {
      if (!db) db = await idbOpen();
      const data = new Uint8Array(10 * 1024 * 1024);
      for (let i = 0; i < data.length; i++) data[i] = (i ^ (i >> 8)) & 0xff;
      const checksum = fnvSample(data);
      const t0 = nowMs();
      await idbPut(db, { id: "pack-sim", ts: new Date().toISOString(),
                         checksum: checksum, data: data });
      const writeMs = Math.round(nowMs() - t0);
      const t1 = nowMs();
      const back = await idbGet(db, "pack-sim");
      const readMs = Math.round(nowMs() - t1);
      const ok = !!(back && back.data && fnvSample(back.data) === checksum);
      push("idb-write", ok, "10 MB write " + writeMs + " ms · readback " +
        readMs + " ms · checksum " +
        (ok ? "verified (" + checksum + ")" : "MISMATCH"));
    } catch (e) { push("idb-write", false, e.message || String(e)); }
    if (db) { try { db.close(); } catch (e) { /* already closed */ } }

    // 7. document settings through the common API
    try {
      const st = (typeof Office !== "undefined" && Office.context &&
                  Office.context.document &&
                  Office.context.document.settings)
        ? Office.context.document.settings : null;
      if (!st) {
        push("settings", false, "document settings unavailable");
      } else {
        const iso = new Date().toISOString();
        st.set("sb-spike", iso);
        await new Promise((resolve, reject) => {
          st.saveAsync((r) => {
            if (r.status === Office.AsyncResultStatus.Succeeded) resolve();
            else reject(new Error((r.error && r.error.message) ||
                                  "saveAsync failed"));
          });
        });
        const got = st.get("sb-spike");
        push("settings", got === iso, "set + saveAsync + get " +
          (got === iso ? "roundtripped (" + got + ")"
                       : "MISMATCH (" + got + ")"));
      }
    } catch (e) { push("settings", false, e.message || String(e)); }

    // 8. the line ADR-001 will quote
    push("summary", true, "platform=" + platform + " · " + survival +
         " · persisted=" + persistedNow);
  } finally {
    runSpike.busy = false;
  }
}

/* Control census: every content control the API can see, tag and title,
 * so a click-test can read the document's control state at any moment. */
async function runCensus() {
  const res = { when: new Date().toISOString(), kind: "control-census",
                count: 0, controls: [] };
  try {
    await Word.run(async (ctx) => {
      const ccs = ctx.document.contentControls;
      ccs.load("items/tag,items/title");
      await ctx.sync();
      res.count = ccs.items.length;
      res.controls = ccs.items.map((c) => ({
        tag: c.tag || "(no tag)",
        title: c.title || "untitled",
      }));
    });
  } catch (e) {
    res.error = e.message || String(e);
  }
  renderDiag(res);
}

async function copyDiag() {
  const btn = $("btn-diag-copy");
  const flash = (msg) => {
    btn.textContent = msg;
    setTimeout(() => { btn.textContent = "Copy results"; }, 1400);
  };
  if (!DIAG_LAST) { flash("Nothing yet"); return; }
  const text = JSON.stringify(DIAG_LAST);
  try {
    if (!(navigator.clipboard && navigator.clipboard.writeText)) {
      throw new Error("no async clipboard");
    }
    await navigator.clipboard.writeText(text);
    flash("Copied ✓");
  } catch (e) {
    // hidden-textarea fallback for webviews without the async clipboard
    const ta = document.createElement("textarea");
    ta.value = text;
    ta.setAttribute("readonly", "");
    ta.style.position = "fixed";
    ta.style.top = "-1000px";
    document.body.appendChild(ta);
    ta.focus();
    ta.select();
    let ok = false;
    try { ok = document.execCommand("copy"); } catch (e2) { ok = false; }
    ta.remove();
    flash(ok ? "Copied ✓" : "Copy failed");
  }
}

/* ----------------------------------------------------------------- boot */

Office.onReady(async (info) => {
  // diagnostics first: the drawer must work even when the pack data or
  // the host check fails, so the spike can run anywhere the pane loads
  $("btn-spike").addEventListener("click", runSpike);
  $("btn-census").addEventListener("click", runCensus);
  $("btn-diag-copy").addEventListener("click", copyDiag);
  if (info.host !== Office.HostType.Word) {
    setStatus("Sidebar only works inside Word.", "err");
    return;
  }
  try {
    const [mods, firm] = await Promise.all([
      fetch("modules.json").then((r) => r.json()),
      fetch("firm.json").then((r) => r.json()),
    ]);
    DATA = mods;
    FIRM = firm;
    CONV = firm.conventions;
    WHEREFORE_RX = new RegExp(CONV.wherefore_regex);
  } catch (e) {
    setStatus("Could not load the pack data (modules.json / firm.json). " +
              "Is the dev server running? node server/dev-serve.js", "err");
    return;
  }
  $("firm-line").textContent = FIRM.firm.display;
  const sel = $("def-part");
  for (const p of DATA.parts) {
    const opt = document.createElement("option");
    opt.value = partValue(p);
    opt.textContent = partTitle(p);
    sel.appendChild(opt);
  }
  renderSlots();
  renderAttorneys();
  $("btn-finalize").addEventListener("click", finalize);
  $("btn-refresh").addEventListener("click", refreshCurrent);
  $("def-search").addEventListener("input", renderBank);
  $("def-part").addEventListener("change", renderBank);
  $("def-search").placeholder =
    "Search " + DATA.modules.length + " defenses...";
  renderBank();
  await refreshCurrent();
  setStatus("Ready. " + DATA.modules.length + " defenses loaded for " +
            FIRM.firm.display + ".", "ok");
});
